### ISSUE TITLE
Restore windows after full screen magit-status

### ISSUE THREAD

**Issue by sr105** [lunaryorn/lunaryorn.github.io#24]
<https://github.com/lunaryorn/lunaryorn.github.io/blob/ab936d75788fb0cb169d3d4dc75d9c32a26f0d72/_posts/2016-04-28-fullscreen-magit-status.md>

Have you seen this code regarding saving the current window layout and restoring it later?

<http://whattheemacsd.com/setup-magit.el-01.html>

**Comment by lunaryorn** [comment]
@sr105 No I've not.  I'm not sure what it adds, though?  Magit seems to save and restore the window layout on its own anyway, at least in the recent MELPA versions, doesn't it?
