### ISSUE TITLE
Post about my Spacemacs experience

### ISSUE THREAD

**Issue by lunaryorn** [lunaryorn/lunaryorn.github.io#5]

**Comment by rejeep** [comment]
Awesome! :+1: :heart: :smile:

**Comment by tonini** [comment]
Yes! :yellow_heart: :blue_heart: :green_heart:

**Comment by manuel-uberti** [comment]
Yeah! Can't wait!

(no pressure, of course :smile:)

**Comment by lunaryorn** [comment]
It took a long time, but I've finally a complete draft post about why I like Spacemacs, at https://github.com/lunaryorn/lunaryorn.github.io/blob/master/_drafts/why-spacemacs.md.  I'll proof-read it over the next days, and then publish it.

The next post in the pipeline is about my experience with switching to Spacemacs, see #21 :)

**Comment by rejeep** [comment]
<3

**Comment by manuel-uberti** [comment]
Great, thank you!
